# Generated by Django 2.1.15 on 2020-03-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0041_auto_20191030_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link_id', models.CharField(max_length=1000)),
                ('context_id', models.CharField(max_length=1000)),
                ('instance_guid', models.CharField(max_length=1000)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.NewExam')),
            ],
        ),
    ]
