# Generated by Django 2.1.15 on 2020-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_editor_lti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticontext',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
