# Generated by Django 2.0.1 on 2018-01-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0024_auto_20180118_1135'),
        ('editor', '0027_customparttype_ready_to_use'),
    ]

    operations = [
    ]
