# Generated by Django 2.0.5 on 2018-05-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0029_customparttype_help_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customparttype',
            name='copy_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='editor.CustomPartType'),
        ),
    ]
