# Generated by Django 2.0.5 on 2018-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0030_customparttype_copy_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editoritem',
            name='taxonomy_nodes',
            field=models.ManyToManyField(related_name='editoritems', to='editor.TaxonomyNode'),
        ),
        migrations.AlterField(
            model_name='question',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='questions', to='editor.Image'),
        ),
    ]
