# Generated by Django 2.0.5 on 2018-06-26 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0031_auto_20180510_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editoritem',
            name='access_rights',
            field=models.ManyToManyField(blank=True, editable=False, related_name='accessed_items', through='editor.Access', to=settings.AUTH_USER_MODEL),
        ),
    ]
