# Generated by Django 2.0.5 on 2018-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0035_customparttype_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='runs_headless',
            field=models.BooleanField(default=True, help_text='Can this extension run outside a browser?'),
        ),
    ]
