# Generated by Django 2.1.11 on 2019-10-18 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0039_extension_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('view', 'Can view'), ('edit', 'Can edit')], default='view', max_length=6)),
            ],
            bases=(models.Model, editor.models.TimelineMixin),
        ),
        migrations.AlterField(
            model_name='extension',
            name='url',
            field=models.CharField(blank=True, help_text='Address of a page about the extension. Leave blank to use the README file.', max_length=300, verbose_name='Documentation URL'),
        ),
        migrations.AddField(
            model_name='extensionaccess',
            name='extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='editor.Extension'),
        ),
        migrations.AddField(
            model_name='extensionaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_accesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
