# Generated by Django 2.2.6 on 2019-10-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0040_auto_20191018_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='editor.Folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='editor.Project')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('name', 'project', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='editoritem',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='editor.Folder'),
        ),
    ]
