# Generated by Django 2.1.11 on 2019-10-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0041_auto_20191029_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('slug', 'project', 'parent')},
        ),
    ]
