# Generated by Django 2.1.15 on 2020-04-20 13:58

from django.db import migrations, models
import django.utils.timezone

def set_stamp_dates(apps, schema_editor):
    NewStampOfApproval = apps.get_model('editor','NewStampOfApproval')
    TimelineItem = apps.get_model('editor','TimelineItem')

    ContentType = apps.get_model('contenttypes','ContentType')

    ct_stamp = ContentType.objects.get_for_model(NewStampOfApproval)

    for s in NewStampOfApproval.objects.all():
        try:
            ti = TimelineItem.objects.filter(object_content_type=ct_stamp,object_id=s.pk).first()
            s.date = ti.date
            s.save()
        except TimelineItem.DoesNotExist:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0042_tip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstampofapproval',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='newstampofapproval',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_stamp_dates, migrations.RunPython.noop)
    ]
