# Generated by Django 2.1.15 on 2020-04-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0043_auto_20200420_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editoritem',
            name='watching_users',
        ),
    ]
