# Generated by Django 2.2.13 on 2020-08-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0045_auto_20200421_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='alt_text',
            field=models.TextField(blank=True),
        ),
    ]
