# Generated by Django 3.1 on 2020-08-27 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0047_auto_20200827_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('view', 'Can view'), ('edit', 'Can edit')], default='view', max_length=6)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='editor.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, editor.models.TimelineMixin),
        ),
    ]
