# Generated by Django 3.1 on 2020-10-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0048_themeaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaccess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectaccess', to='editor.project'),
        ),
    ]
