# Generated by Django 3.1 on 2020-10-29 10:46
from django.db import migrations

from django.core.management import call_command

def load_fixtures(apps, schema_editor):
    for fixture in ('abilitylevels', 'subjects-topics', 'taxonomies'):
        call_command('loaddata', fixture, app_label='editor') 

def unload_fixtures(apps, schema_editor):
    for model_name in ("AbilityLevel", "AbilityFramework", "Subject", "Topic", "Taxonomy", "TaxonomyNode"):
        model = apps.get_model("editor", model_name)
        model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0051_auto_20201027_1547'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_code=unload_fixtures),
    ]
