# Generated by Django 3.1 on 2021-03-08 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0053_auto_20210308_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False, help_text='Can this knowledge graph be seen by everyone?')),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_knowledge_graphs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('knowledge_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='editor.knowledgegraph')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('depends_on', models.ManyToManyField(related_name='used_by', to='editor.Topic')),
                ('knowledge_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='editor.knowledgegraph')),
                ('learning_objectives', models.ManyToManyField(related_name='topics', to='editor.LearningObjective')),
            ],
        ),
        migrations.AddField(
            model_name='newquestion',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='editor.Topic'),
        ),
    ]
