# Generated by Django 3.2.5 on 2021-11-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0055_customparttypeaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchangedtimelineitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_changed_timelineitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
