# Generated by Django 3.2.5 on 2021-11-16 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0056_auto_20211109_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.project')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQueueChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='editor.itemqueue')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQueueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.editoritem')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.itemqueue')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQueueChecklistTick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.itemqueueentry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.itemqueuechecklistitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
