# Generated by Django 3.2.5 on 2021-11-18 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def delete_timeline_items(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    TimelineItem = apps.get_model('editor','TimelineItem')

    for pk in TimelineItem.objects.order_by('object_content_type').values_list('object_content_type',flat=True).distinct():
        ct = ContentType.objects.get(pk=pk)
        try:
            model = apps.get_model(ct.app_label, ct.model)
        except LookupError:
            TimelineItem.objects.filter(object_content_type=pk).delete()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0058_auto_20211117_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customparttypeaccess',
            name='custom_part_type',
        ),
        migrations.RemoveField(
            model_name='customparttypeaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='extensionaccess',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='extensionaccess',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='projectaccess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectaccess',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='themeaccess',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='themeaccess',
            name='user',
        ),
        migrations.RemoveField(
            model_name='editoritem',
            name='access_rights',
        ),
        migrations.RemoveField(
            model_name='project',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.DeleteModel(
            name='CustomPartTypeAccess',
        ),
        migrations.DeleteModel(
            name='ExtensionAccess',
        ),
        migrations.DeleteModel(
            name='ProjectAccess',
        ),
        migrations.DeleteModel(
            name='ThemeAccess',
        ),
        migrations.RunPython(delete_timeline_items, migrations.RunPython.noop),
    ]
