# Generated by Django 3.2.5 on 2022-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0058_queues_remove_old_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customparttype',
            name='input_widget',
            field=models.CharField(max_length=200, verbose_name='Answer input method'),
        ),
    ]
