# Generated by Django 3.2.12 on 2022-05-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0059_alter_customparttype_input_widget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemqueuechecklistitem',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='itemqueuechecklistitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
