# Generated by Django 3.2.5 on 2021-11-22 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0059_auto_20211118_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemqueue',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemqueue',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemqueue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='editor.project'),
        ),
        migrations.AlterField(
            model_name='itemqueuechecklisttick',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='editor.itemqueueentry'),
        ),
        migrations.AlterField(
            model_name='itemqueuechecklisttick',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='editor.itemqueuechecklistitem'),
        ),
        migrations.AlterField(
            model_name='itemqueuechecklisttick',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry_ticks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemqueueentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemqueueentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='editor.editoritem'),
        ),
        migrations.AlterField(
            model_name='itemqueueentry',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='editor.itemqueue'),
        ),
    ]
