# Generated by Django 3.2.5 on 2021-11-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0061_remove_editoritem_public_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemqueueentry',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='itemqueue',
            name='instructions',
        ),
        migrations.AddField(
            model_name='itemqueue',
            name='instructions_reviewer',
            field=models.TextField(blank=True, verbose_name='Instructions for reviewers'),
        ),
        migrations.AddField(
            model_name='itemqueue',
            name='instructions_submitter',
            field=models.TextField(blank=True, verbose_name='Instructions for submitters'),
        ),
        migrations.AlterField(
            model_name='itemqueue',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Visible to everyone?'),
        ),
    ]
