# Generated by Django 4.1.3 on 2022-12-14 08:27

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0063_alter_abilityframework_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editoritem',
            options={'ordering': (django.db.models.functions.text.Lower('name'),), 'permissions': [('view_everything', 'Can view everything')]},
        ),
    ]
