# Generated by Django 4.2.6 on 2025-03-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0065_resource_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('outfile', models.FileField(upload_to='exports/', verbose_name='Output file')),
                ('status', models.CharField(choices=[('inprogress', 'In progress'), ('complete', 'Complete'), ('error', 'Error')], default='inprogress', max_length=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Time this report was created')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
                ('object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Data export',
                'verbose_name_plural': 'Data exports',
                'ordering': ('-creation_time',),
            },
        ),
    ]
