# Generated by Django 4.2.6 on 2025-03-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0066_dataexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataexport',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('inprogress', 'In progress'), ('complete', 'Complete'), ('error', 'Error')], default='queued', max_length=10),
        ),
    ]
