# Generated by Django 5.2 on 2026-08-06 10:08

from django.db import migrations
from pathlib import Path

from editor.file_storage import hashed_name

def hash_existing_files(apps, schema_editor):
    Resource = apps.get_model('editor', 'Resource')

    field = Resource.file.field
    root = Path(field.storage.location)
    upload_to = root / field.upload_to

    linked_names = list(Resource.objects.values_list('file', flat=True))
    for p in (upload_to).iterdir():
        if not p.is_file():
            continue

        s = str(p.relative_to(root))

        if s not in linked_names:
            print(f"Delete {s}")
            p.unlink()

    for r in Resource.objects.all():
        with r.file.open() as f:
            n = hashed_name(r.file.name, f)

        original_path = root / r.file.name

        new_path = upload_to / Path(n).name

        if original_path == new_path:
            continue

        print(f"Moving {original_path.relative_to(root)} to {new_path.relative_to(root)}")

        if new_path.exists():
            original_path.unlink()
        else:
            original_path.rename(new_path)

        with new_path.open('rb') as f:
            r.file.save(new_path.relative_to(upload_to), f)

class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0067_dataexport_error_message_alter_dataexport_status'),
    ]

    operations = [
        migrations.RunPython(hash_existing_files, migrations.RunPython.noop),
    ]
