# Generated by Django 5.2 on 2026-10-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0068_hash_uploaded_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='theme',
            name='zipfile',
            field=models.FileField(blank=True, help_text="A .zip package containing the theme's files", max_length=255, null=True, upload_to='user-themes/zips', verbose_name='Theme package'),
        ),
        migrations.AddField(
            model_name='theme',
            name='compiler',
            field=models.ForeignKey(blank=True, help_text='If blank, the default compiler is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='editor.compiler'),
        ),
    ]
