# Generated by Django 2.1.15 on 2020-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_editoritemviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_about_comments',
            field=models.BooleanField(default=True, verbose_name="Send emails about comments on items you're watching?"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_about_stamps',
            field=models.BooleanField(default=True, verbose_name="Send emails about feedback on items you're watching?"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='never_email',
            field=models.BooleanField(default=False, verbose_name='Unsubscribe from all emails'),
        ),
    ]
