# Generated by Django 3.2.5 on 2021-12-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200421_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_about_item_queue_entries',
            field=models.BooleanField(default=True, verbose_name="Send emails about entries on item queues you're watching?"),
        ),
    ]
