# Generated by Django 4.2.6 on 2025-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userprofile_email_about_item_queue_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mathjax_3_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Preferred URL to load MathJax 3 from'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mathjax_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Preferred URL to load MathJax 2 from'),
        ),
    ]
