# Generated by Django 4.2.6 on 2025-04-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_userprofile_mathjax_3_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mathjax_url',
            new_name='mathjax_2_url',
        ),
    ]
