# Generated by Django 3.1 on 2020-10-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('feature', models.CharField(max_length=1000)),
                ('date_observed', models.DateTimeField(auto_now=True)),
                ('object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='contenttypes.contenttype')),
            ],
        ),
    ]
